Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

AllCops:
  NewCops: enable
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call