version: '3'

services:
  rails-app:
    build:
      context: ./rails-app
      dockerfile: Dockerfile
    image: hraynaud/konmego-rails:latest
    container_name: konmego-rails:latest
    ports:
      - "3000:3000"
    depends_on:
      - neo4j-db
    environment:
      - NEO4J_URL=bolt://neo4j-db:7687
      - NEO4J_HOST=neo4j-db
      - NEO4J_PORT=7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
  neo4j-db:
    image: neo4j:community-bullseye
    container_name: konmego-neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - /home/ec2-user/neo4j-data:/data  

networks:
  default:
    name: konmego-network
