development:
  url: "<%= ENV['NEO4J_URL'] %>"
  username: "<%= ENV['NEO4J_USER'] %>"
  password: "<%= ENV['NEO4J_PASSWORD'] %>"
test:
  url: bolt://localhost:7570  
  username: neo4j
  password: password
production:
  url:
    - neo4j://core1:7687
    - neo4j://core2:7687
    - neo4j://core3:7687
  username: neo4j
  password: password
