development:
  url: "neo4j://<%= ENV['NEO4J_HOST'] %>:<%= ENV['NEO4J_PORT'] %>"
  username: "<%= ENV['NEO4J_USER'] %>"
  password: "<%= ENV['NEO4J_PASSWORD'] %>"
test:
  url: bolt://localhost:7570
  username: neo4j
  password: password
production:
  url:
    - neo4j://core1:7687
    - neo4j://core2:7687
    - neo4j://core3:7687
  username: neo4j
  password: password
