development:
  url: bolt://localhost:7472

test:
  url: bolt://localhost:7687

#  url: bolt://localhost:7876 old value
production:
  url:
    - neo4j://core1:7687
    - neo4j://core2:7687
    - neo4j://core3:7687
  username: neo4j
  password: password
